//SCAPS SCRIPT
//THIS SCRIPT CALCULATES THE IV CURVE OF THE SERIES CONNECTION OF TWO CELLS

//SETTING THE STARTING CONDITIONS
clear all
clear actions
action light
action iv.startv 0
action iv.stopv 3.0
action iv.increment 0.02
action iv.checkaction
action iv.stopaftervoc

//cell 1 high BG
load definitionfile Ba2ZnOsO6.def
calculate singleshot
get iv zu

//cell 2 low BG
load definitionfile Ba2PrPtO6.def
calculate singleshot
get iv vw

//calculate the IV of the series connection
math series xyzuvw nz

//visualize the results
plot draw zu
plot draw vw
plot draw xy

math characteristics.all cxy
math characteristics.voc XXY
math characteristics.jsc yxy
math characteristics.ff zxy
math characteristics.eta uxy
math characteristics.vmpp vxy
math characteristics.jmpp wxy

show scriptvariables





